import json
import requests
from typing import Dict, Any, Optional, Iterator

class OrchestratorRESTClient:
    """
    A robust client for interacting with the Nemotron Orchestrator service.
    """

    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Content-Type": "application/json",
            "Accept": "application/json"
        })

    def check_health(self) -> bool:
        """Verifies if the orchestrator service is online and accepting connections."""
        try:
            response = self.session.get(f"{self.base_url}/health", timeout=5.0)
            response.raise_for_status()
            return response.json().get("ok") is True
        except requests.RequestException as e:
            print(f"Health check failed: {e}")
            return False
            
    def _handle_error(self, response: requests.Response) -> None:
        """Extracts JSON error payloads for cleaner console debugging."""
        try:
            error_data = response.json()
            error_msg = error_data.get("error", {}).get("message", response.text)
            print(f"\n[Server Error]: {error_msg}")
        except ValueError:
            pass
        response.raise_for_status()

    def generate_completion(
        self,
        task: str,
        schema: str,
        dialect: str = "sqlite3",
        model: str = "nemotron-orchestrator-sql-python",
        stream: bool = False,
        max_turns: int = 8,
        route_mode: str = "hybrid"
    ) -> Any:
        """
        Submits a task to the orchestrator using the OpenAI-compatible chat/completions endpoint.
        """
        url = f"{self.base_url}/v1/chat/completions"
        
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": task}],
            "stream": stream,
            # Orchestrator-specific extensions
            "schema": schema,
            "dialect": dialect,
            "max_turns": max_turns,
            "route_mode": route_mode,
            "temperature": 0.0, # Deterministic routing prefers 0.0
        }

        if stream:
            return self._handle_streaming_response(url, payload)
        
        return self._handle_synchronous_response(url, payload)

    def _handle_synchronous_response(self, url: str, payload: Dict[str, Any]) -> str:
        """Processes a standard, blocking JSON response."""
        response = self.session.post(url, json=payload, timeout=300.0)
        
        if not response.ok:
            self._handle_error(response)
            
        data = response.json()
        choices = data.get("choices", [])
        if choices:
            return choices[0].get("message", {}).get("content", "")
        return ""

    def _handle_streaming_response(self, url: str, payload: Dict[str, Any]) -> Iterator[str]:
        """
        Processes a Server-Sent Events (SSE) stream.
        Yields text chunks as they are generated by the orchestrator.
        """
        # Ensure we request the correct content type for streaming
        headers = {"Accept": "text/event-stream"}
        
        with self.session.post(url, json=payload, headers=headers, stream=True, timeout=300.0) as response:
            if not response.ok:
                self._handle_error(response)
                
            for line in response.iter_lines(decode_unicode=True):
                if line:
                    if line.startswith("data: "):
                        data_str = line[6:]
                        if data_str == "[DONE]":
                            break
                        
                        try:
                            chunk = json.loads(data_str)
                            choices = chunk.get("choices", [])
                            if choices:
                                delta = choices[0].get("delta", {})
                                content = delta.get("content")
                                if content:
                                    yield content
                        except json.JSONDecodeError:
                            continue

# --- Example Execution ---
if __name__ == "__main__":
    client = OrchestratorRESTClient()
    
    if client.check_health():
        print("Orchestrator is online! Initiating task...\n")
        
        test_schema = """
        CREATE TABLE employees (
          id INTEGER PRIMARY KEY,
          name TEXT NOT NULL,
          department TEXT,
          salary NUMERIC NOT NULL
        );
        """
        
        test_task = "Write a simple Python main-style application that queries a sqlite3 database to return the employee who has the highest salary."
        
        print("Streaming response:\n")
        # Demonstrating the streaming capability 
        stream_generator = client.generate_completion(
            task=test_task,
            schema=test_schema,
            dialect="sqlite3",
            stream=True
        )
        
        for text_chunk in stream_generator:
            print(text_chunk, end="", flush=True)
            
        print("\n\nTask execution concluded.")
    else:
        print("Failed to connect to the orchestrator. Is the service running?")